import { Poppins } from "next/font/google";
import "./globals.css";
import Title from "@/components/Title";
import { TranslatorProvider } from '@/context/context'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "IA Code Translator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <TranslatorProvider>
          <Title />
          {children}
        </TranslatorProvider>
      </body>
    </html>
  );
}
